query GetTransactions($skip: Int!, $limit: Int!) {
    transactions(_skip: $skip, _limit: $limit) {
        id
        user_id
        description
        merchant_id
        debit
        credit
        amount
    }
}
