query GetTransactions($skip: Int!, $limit: Int!) {
    transactions(_skip: $skip, _limit: $limit) {
        id
        user {
            id,
            firstName,
            lastName
        }
        description
        merchant {
            id,
            name,
            description
        }
        debit
        credit
        amount
    }
}
